// Runs in the user's own Python interpreter: `python -c <script> <strategies...>` with the cell on
// stdin, printing {"via", "code"} as JSON. Each strategy's output is kept only when it differs from
// the source in layout alone (whitespace, parentheses, commas, semicolons, line continuations).
export const PYTHON_FORMATTER_SCRIPT = [
	"import ast, io, json, re, shutil, subprocess, sys, tokenize",
	"",
	"def emit(via, code):",
	"    sys.stdout.write(json.dumps({'via': via, 'code': code}))",
	"    sys.exit(0)",
	"",
	"def same_tokens(left, right):",
	"    strip = lambda text: re.sub(r'[\\s(),;\\\\]', '', text)",
	"    return strip(left) == strip(right)",
	"",
	"def ruff_binary():",
	"    found = shutil.which('ruff')",
	"    if found:",
	"        return found",
	"    try:",
	"        from ruff.__main__ import find_ruff_bin",
	"        return find_ruff_bin()",
	"    except Exception:",
	"        return None",
	"",
	"def with_ruff(source):",
	"    binary = ruff_binary()",
	"    if not binary:",
	"        return None",
	"    args = [binary, 'format', '--quiet', '--no-cache', '--config', \"format.quote-style = 'preserve'\",",
	"            '--stdin-filename', 'cell.py', '-']",
	"    try:",
	"        done = subprocess.run(args, input=source, capture_output=True, text=True, timeout=4)",
	"    except Exception:",
	"        return None",
	"    return done.stdout if done.returncode == 0 else None",
	"",
	"def with_black(source):",
	"    try:",
	"        import black",
	"        return black.format_str(source, mode=black.Mode(string_normalization=False))",
	"    except Exception:",
	"        return None",
	"",
	"def token_kinds(*names):",
	"    return {getattr(tokenize, name) for name in names if hasattr(tokenize, name)}",
	"",
	"def literal_spans(source):",
	"    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))",
	"    starts = [0]",
	"    for line in source.splitlines(keepends=True):",
	"        starts.append(starts[-1] + len(line))",
	"    offset = lambda position: starts[position[0] - 1] + position[1]",
	"    opening, closing = token_kinds('FSTRING_START', 'TSTRING_START'), token_kinds('FSTRING_END', 'TSTRING_END')",
	"    spans, depth = [], 0",
	"    for token in tokens:",
	"        if token.type == tokenize.COMMENT:",
	"            return None",
	"        if depth:",
	"            depth += 1 if token.type in opening else -1 if token.type in closing else 0",
	"            if depth == 0:",
	"                spans[-1][1] = offset(token.end)",
	"            continue",
	"        is_string = token.type == tokenize.STRING or token.type in opening",
	"        if not is_string and token.type != tokenize.NUMBER:",
	"            continue",
	"        start, end = offset(token.start), offset(token.end)",
	"        joined = spans and spans[-1][2] and is_string and not re.sub(r'[\\s\\\\]', '', source[spans[-1][1]:start])",
	"        if joined:",
	"            spans[-1][1] = end",
	"        else:",
	"            spans.append([start, end, is_string])",
	"        if token.type in opening:",
	"            depth = 1",
	"    return spans",
	"",
	"def with_ast(source):",
	"    if not hasattr(ast, 'unparse'):",
	"        return None",
	"    try:",
	"        spans = literal_spans(source)",
	"    except (tokenize.TokenError, SyntaxError):",
	"        return None",
	"    if spans is None:",
	"        return None",
	"    prefix = '_display'",
	"    while prefix in source:",
	"        prefix += '_'",
	"    raws, masked, cursor = {}, [], 0",
	"    for index, (start, end, _) in enumerate(spans):",
	"        name = prefix + str(index)",
	"        raws[name] = source[start:end]",
	"        masked.append(source[cursor:start] + name)",
	"        cursor = end",
	"    masked.append(source[cursor:])",
	"    try:",
	"        flags = ast.PyCF_ONLY_AST | getattr(ast, 'PyCF_ALLOW_TOP_LEVEL_AWAIT', 0)",
	"        tree = compile(''.join(masked), '<cell>', 'exec', flags=flags, dont_inherit=True)",
	"    except (SyntaxError, ValueError):",
	"        return None",
	"    seen = []",
	"    def restore(match):",
	"        seen.append(match.group(0))",
	"        return raws.get(match.group(0), match.group(0))",
	"    text = re.sub(r'\\b' + re.escape(prefix) + r'\\d+\\b', restore, ast.unparse(tree))",
	"    return text if sorted(seen) == sorted(raws) else None",
	"",
	"STRATEGIES = {'ruff': with_ruff, 'black': with_black, 'ast': with_ast}",
	"source = sys.stdin.read()",
	"for name in sys.argv[1:]:",
	"    strategy = STRATEGIES.get(name)",
	"    formatted = strategy(source) if strategy else None",
	"    if formatted is not None and same_tokens(formatted, source):",
	"        emit(name, formatted.rstrip('\\n'))",
	"emit('none', source)",
].join("\n");
