[package]
name = "senpi-desktop-backend-win32"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[target.'cfg(target_os = "windows")'.dependencies]
enigo.workspace = true
uiautomation.workspace = true
windows-sys.workspace = true
xcap.workspace = true
